"""
GOLDEN WISHES — Seed data generator
--------------------------------------------------------
Generates realistic, anonymized demo data for:
organizations, beneficiaries, wishes, donors, donations, news_items

Every wish is hand-written (unique title, description and story) so the
detail pages, the AI chatbot (RAG) and the trust check all get meaningful text.
Faker is only used for donors and organization contacts.

Requirements:
    pip install faker

Run order on a fresh database:
    1. schema.sql
    2. migrations/001_golden_wishes_features.sql
    3. seed_data.sql   (generated by this script)

Usage:
    python3 generate_seed_data.py
Outputs:
    seed_data.sql   -> run against Postgres (psql "$DATABASE_URL" -f seed_data.sql)
    seed_data.json  -> same data as JSON
"""

import json
import random
import uuid
from datetime import datetime, timedelta

from faker import Faker

fake = Faker("en_US")
Faker.seed(42)
random.seed(42)

NOW = datetime(2026, 9, 27, 10, 0, 0)
PLACEHOLDER_ORG = "Independent submissions (to be assigned)"  # created by migration 001


class Raw(str):
    """A value written into the SQL as-is (e.g. a subquery), not quoted."""


# ------------------------------------------------------------
# Places and organizations (all fictional)
# One official spelling per region, used everywhere.
# ------------------------------------------------------------
ORGANIZATIONS = {
    "casablanca": ("Al Amal Children's Association", "ngo", "Casablanca", "Casablanca-Settat", True),
    "ouarzazate": ("Tighremt Solidarity Association", "ngo", "Ouarzazate", "Drâa-Tafilalet", True),
    "agadir": ("Souss Children's Aid", "ngo", "Agadir", "Souss-Massa", True),
    "marrakech": ("Dar Al Farah Children's Home", "orphanage", "Marrakech", "Marrakech-Safi", True),
    "tangier": ("Ennour Community Center", "community_center", "Tangier", "Tanger-Tétouan-Al Hoceïma", True),
    "rabat": ("Bouregreg Family Support Network", "ngo", "Rabat", "Rabat-Salé-Kénitra", True),
    "oujda": ("Hope Foundation Oujda", "ngo", "Oujda", "L'Oriental", True),
    "fes": ("Medina Children's Circle", "community_center", "Fès", "Fès-Meknès", False),
}

GIRL_NAMES = ["Amara", "Salma", "Lina", "Nour", "Yasmine", "Kenza", "Malak", "Sara", "Imane",
              "Hiba", "Rim", "Aya", "Douaa", "Chaimae", "Ghita", "Meryem", "Hajar", "Wiam",
              "Zineb", "Oumaima"]
BOY_NAMES = ["Youssef", "Adam", "Rayan", "Ilyas", "Zayd", "Hamza", "Anas", "Mehdi", "Othmane",
             "Walid", "Bilal", "Karim", "Ayoub", "Idriss", "Nassim", "Saad", "Taha", "Amine",
             "Yassine", "Soufiane"]

# ------------------------------------------------------------
# Hand-written wishes
# (key, gender, age range, situation, category, cost MAD, urgency, funding, tags,
#  title, description, story)
# funding: open | partial | almost (80-95%) | funded | delivered
# {name} and {age} are filled from the beneficiary. Stories stay anonymized:
# nickname only, no surname, no address, no school or hospital name.
# ------------------------------------------------------------
WISHES = [
    # --- Casablanca-Settat ---
    ("casablanca", "F", (7, 9), "family_in_difficulty", "education", 180, "medium", "open",
     ["school", "supplies", "back-to-school"],
     "A fully stocked school bag",
     "Notebooks, pens, a pencil case and a bag strong enough for the whole year.",
     "{name} is {age} and starts the new school year in a few weeks. Her mother cleans offices at night "
     "and this month's money has already gone to rent. Last year {name} shared notebooks with her cousin "
     "and often could not do her homework. A bag of her own would let her start the year like everyone else."),
    ("casablanca", "M", (9, 12), "family_in_difficulty", "health", 320, "high", "almost",
     ["health", "vision", "school"],
     "Prescription glasses to read the board",
     "An eye test showed he needs glasses; the family cannot cover frames and lenses.",
     "{name}, {age}, has been squinting at the board since the start of the year. An eye test at the local "
     "health center confirmed he needs glasses, but the family could not afford them. His teacher noticed "
     "his marks dropping in every subject. With glasses, he could simply see what everyone else sees."),
    ("casablanca", "F", (5, 8), "family_in_difficulty", "food", 650, "high", "partial",
     ["food", "family", "urgent"],
     "A month of groceries for a family of six",
     "Flour, oil, rice, lentils, milk and vegetables for four weeks.",
     "{name}'s father was injured on a construction site and cannot work for two months. Her mother now "
     "looks after four children alone. The family has started skipping dinner so the youngest can eat. "
     "One month of groceries would carry them until her father is back on his feet."),
    ("casablanca", "F", (17, 17), "family_in_difficulty", "technology", 2400, "medium", "partial",
     ["technology", "education", "baccalaureate"],
     "A secondhand laptop for a final-year student",
     "A reliable used laptop for revision, research and online mock exams.",
     "{name} is {age} and in her final year before the baccalaureate. She is one of the best students in "
     "her class and dreams of studying engineering. She types her assignments on her phone, late at night, "
     "after helping her younger siblings. A laptop would give her the same chance as her classmates."),
    ("casablanca", "M", (11, 13), "temporary_placement", "sport", 260, "low", "open",
     ["sport", "football", "hobby"],
     "Football boots and shin guards",
     "Proper boots and shin guards so he can join training safely.",
     "{name}, {age}, plays football every evening in sandals. His coach at the neighborhood club says he has "
     "real talent but cannot let him play matches without proper boots. Football is what keeps him going "
     "since he was placed in a foster home. A pair of boots would let him play with his team."),

    # --- Drâa-Tafilalet (demo region: storm in Ouarzazate) ---
    ("ouarzazate", "M", (6, 9), "family_in_difficulty", "shelter", 900, "critical", "partial",
     ["shelter", "storm", "roof", "urgent"],
     "A waterproof tarp and roof repair kit",
     "Tarp, beams and sealant to close the roof damaged by the storm.",
     "Last week's storm tore open part of the roof of {name}'s home. The family of five now sleeps in the one "
     "room that stays dry. {name}, {age}, has been coughing since the rain came in. A tarp and basic repair "
     "materials would make the house safe again before the next storm."),
    ("ouarzazate", "F", (4, 7), "family_in_difficulty", "food", 450, "critical", "open",
     ["food", "storm", "emergency"],
     "An emergency food basket after the storm",
     "Two weeks of staples for a family whose food stock was ruined by flooding.",
     "Floodwater reached the storeroom where {name}'s family kept flour, oil and sugar for the month. "
     "Everything was lost in one night. Her father's work in the fields has stopped until the roads reopen. "
     "An emergency basket would feed {name} and her brothers for the next two weeks."),
    ("ouarzazate", "M", (8, 11), "family_in_difficulty", "shelter", 600, "high", "almost",
     ["shelter", "bedding", "storm", "winter"],
     "Warm bedding for a family of five",
     "Mattresses and wool blankets to replace those soaked by the storm.",
     "The storm soaked every mattress and blanket in {name}'s house. Nights in the valley are already cold, "
     "and the family has been sleeping on dry cardboard. {name}, {age}, keeps his little sister warm with his "
     "jacket. New bedding would give the whole family a proper night's sleep again."),
    ("ouarzazate", "F", (10, 12), "family_in_difficulty", "education", 150, "high", "open",
     ["school", "supplies", "storm"],
     "Replacing school supplies lost in the flood",
     "Notebooks, a calculator, pens and a new schoolbag after the flood.",
     "{name}, {age}, lost her schoolbag and all her notebooks when water flooded her home. School has "
     "reopened, but she sits in class with nothing to write in. She was top of her class last term. "
     "New supplies would let her pick up where she left off."),
    ("ouarzazate", "M", (3, 6), "family_in_difficulty", "essentials", 700, "high", "open",
     ["winter", "heating", "storm"],
     "A gas heater for the winter",
     "A safe gas heater and a first gas bottle for the coldest months.",
     "Winter nights in the region drop close to freezing. {name} is {age} and has had two chest infections "
     "since last year. The family's old heater was damaged in the storm and cannot be repaired. A safe "
     "heater would keep the main room warm through the winter."),

    # --- Souss-Massa ---
    ("agadir", "F", (9, 12), "orphan", "creative", 170, "low", "open",
     ["creativity", "art", "hobby"],
     "Art supplies for a young painter",
     "Watercolors, brushes and a thick sketchbook.",
     "{name}, {age}, fills every scrap of paper she finds with drawings of the sea. The staff at her children's "
     "home say painting is how she talks about her feelings. She has never owned real paints. A small art kit "
     "would mean the world to her."),
    ("agadir", "M", (8, 10), "temporary_placement", "sport", 400, "low", "funded",
     ["sport", "swimming", "safety"],
     "Swimming lessons for the summer",
     "Ten lessons at the municipal pool with a qualified instructor.",
     "{name} lives a few minutes from the beach but has never learned to swim. His caregivers worry every "
     "summer when the children go to the sea. Swimming lessons would keep him safe and give him confidence. "
     "He has asked about them every week since spring."),
    ("agadir", "F", (12, 15), "hospitalization", "health", 1100, "high", "partial",
     ["health", "rehabilitation", "medical"],
     "Physiotherapy after a leg fracture",
     "Twelve physiotherapy sessions so she can walk normally again.",
     "{name}, {age}, broke her leg badly in a fall earlier this year. The bone has healed, but she still "
     "limps and cannot climb stairs without pain. Her doctor prescribed twelve physiotherapy sessions that the "
     "family cannot pay for. Without them, the limp could become permanent."),
    ("agadir", "M", (7, 9), "family_in_difficulty", "education", 120, "medium", "open",
     ["school", "books", "math", "french"],
     "French and math workbooks",
     "The two workbooks required for his class this year.",
     "{name} is {age} and loves numbers. His teacher gives homework from two workbooks that every pupil is "
     "expected to have. {name} copies the exercises from a friend's book during break. His own workbooks "
     "would let him work at home in the evening."),
    ("agadir", "F", (6, 8), "family_in_difficulty", "clothing", 280, "medium", "delivered",
     ["winter", "clothing"],
     "A winter jacket and boots",
     "A warm jacket and waterproof boots for the rainy season.",
     "{name}, {age}, walked to school in canvas shoes all last winter. She often arrived with wet feet and "
     "spent the morning shivering. Her mother sells bread at the market and every dirham goes to food. A jacket "
     "and boots kept her warm and dry this year."),

    # --- Marrakech-Safi ---
    ("marrakech", "F", (0, 1), "family_in_difficulty", "family_care", 420, "high", "almost",
     ["baby", "nutrition", "urgent"],
     "Infant formula for three months",
     "One tin of formula per week for a baby who cannot be breastfed.",
     "{name} is a few months old. Her mother had complications after the birth and cannot breastfeed. Formula "
     "costs more than a third of the family's income. Three months of formula would get {name} to the age "
     "where she can start eating other food."),
    ("marrakech", "M", (12, 14), "family_in_difficulty", "essentials", 950, "medium", "partial",
     ["transport", "school", "bicycle"],
     "A bicycle for the long road to school",
     "A sturdy bicycle, a lock and a helmet.",
     "{name}, {age}, walks more than an hour each way to reach his middle school. In winter he leaves home "
     "before sunrise and often arrives late for the first lesson. His grades have started to slip from "
     "tiredness. A bicycle would cut the trip to twenty minutes."),
    ("marrakech", "F", (8, 11), "chronic_illness", "education", 600, "medium", "open",
     ["education", "disability", "braille"],
     "Braille learning materials",
     "A braille slate, stylus and starter reading books.",
     "{name}, {age}, lost most of her sight after an illness when she was small. A volunteer teacher has started "
     "teaching her braille once a week. She learns fast but has nothing to practice with at home. Her own "
     "materials would let her read on her own for the first time."),
    ("marrakech", "M", (13, 15), "orphan", "creative", 750, "low", "open",
     ["music", "creativity", "hobby"],
     "A keyboard and music lessons",
     "An entry-level keyboard and a term of lessons at the youth center.",
     "{name}, {age}, taught himself a few melodies on an old keyboard at the youth center before it broke. "
     "The staff at his children's home say music is the only time he truly relaxes. A keyboard of his own "
     "and a term of lessons would give him a real way to express himself."),
    ("marrakech", "M", (6, 9), "chronic_illness", "health", 520, "critical", "partial",
     ["health", "medical", "chronic"],
     "A year of respiratory treatment",
     "Inhalers and a spacer to control a chronic breathing condition.",
     "{name}, {age}, has a chronic breathing condition that needs daily treatment. When the inhaler runs out, "
     "he ends up at the emergency room. His mother has had to choose between his medication and rent twice "
     "this year. A year of treatment would keep him out of emergencies."),

    # --- Tanger-Tétouan-Al Hoceïma ---
    ("tangier", "F", (10, 12), "family_in_difficulty", "clothing", 230, "medium", "open",
     ["school", "uniform", "clothing"],
     "A school uniform and shoes",
     "The required uniform and a pair of black school shoes.",
     "{name}, {age}, has been sent home twice because she did not have the school uniform. Her older sister's "
     "uniform no longer fits her. Her father works as a day laborer and has had little work since the summer. "
     "A uniform and shoes would keep her in class."),
    ("tangier", "M", (13, 15), "family_in_difficulty", "education", 380, "low", "partial",
     ["education", "homework", "furniture"],
     "A desk and lamp for homework",
     "A small desk, a chair and a reading lamp.",
     "{name}, {age}, does his homework on the floor of the room he shares with three siblings. After dark, "
     "the only light is the TV. His teachers say he is capable of much more. A desk and a lamp would give "
     "him a quiet corner to study."),
    ("tangier", "F", (7, 10), "chronic_illness", "health", 350, "high", "open",
     ["health", "hearing", "medical"],
     "Hearing aid batteries and care for six months",
     "Batteries, cleaning kit and a check-up for her hearing aids.",
     "{name}, {age}, received hearing aids through a charity program last year. They changed her life at "
     "school, but the batteries run out every week and the family cannot keep up. Without them, she sits in "
     "silence again. Six months of batteries would keep her hearing."),
    ("tangier", "M", (10, 12), "temporary_placement", "sport", 500, "low", "funded",
     ["sport", "football", "club"],
     "A season with the local football club",
     "Membership, jersey and travel to away matches for one season.",
     "{name}, {age}, trained with the local club all spring but could not pay the season membership. The coach "
     "calls him the most hardworking player on the team. Joining the club gave him structure and friends "
     "during a difficult year in foster care."),
    ("tangier", "F", (0, 1), "family_in_difficulty", "family_care", 380, "high", "open",
     ["baby", "hygiene", "family"],
     "Diapers and baby care for two months",
     "Diapers, wipes, cream and baby soap for eight weeks.",
     "{name} is a few months old and the youngest of four. Her mother is raising the children alone since "
     "their father left. Diapers are the expense she struggles with most every week. Two months of baby care "
     "would give her some breathing room."),

    # --- Rabat-Salé-Kénitra ---
    ("rabat", "F", (13, 15), "orphan", "technology", 1600, "low", "partial",
     ["technology", "coding", "education"],
     "Coding club fees and a used tablet",
     "A term at a youth coding club and a secondhand tablet to practice.",
     "{name}, {age}, discovered programming at a free workshop and has not stopped talking about it since. "
     "The youth coding club accepted her, but she needs a device to practice between sessions. She wants to "
     "build an app to help children in her home with their homework."),
    ("rabat", "M", (12, 13), "family_in_difficulty", "education", 240, "medium", "open",
     ["school", "textbooks"],
     "Textbooks for the second year of middle school",
     "The full set of textbooks required for this year.",
     "{name}, {age}, moved up to the second year of middle school with good grades. The required textbooks "
     "cost more than his family spends on food in a week. He currently borrows books from classmates when "
     "they are not using them. His own set would let him keep up."),
    ("rabat", "F", (5, 9), "family_in_difficulty", "shelter", 800, "medium", "almost",
     ["shelter", "bedding", "health"],
     "A mattress to replace a worn-out one",
     "A new mattress for two sisters who share a bed.",
     "{name} and her little sister share a mattress that is more than ten years old. The springs come through "
     "the fabric and the girls wake up with back pain. {name}, {age}, has trouble concentrating at school. "
     "A new mattress would give both girls proper sleep."),
    ("rabat", "M", (8, 10), "family_in_difficulty", "health", 650, "high", "delivered",
     ["health", "dental", "medical"],
     "Dental treatment for two cavities",
     "Treatment for two deep cavities causing constant pain.",
     "{name}, {age}, had toothache for months and could no longer eat properly. A dentist found two deep "
     "cavities that needed treatment quickly. His parents could not cover the cost. The treatment is done "
     "and he is smiling again."),
    ("rabat", "F", (14, 16), "orphan", "creative", 1200, "low", "open",
     ["creativity", "drawing", "comics"],
     "A drawing tablet for a comic book fan",
     "An entry-level graphics tablet and a free drawing software setup.",
     "{name}, {age}, draws her own comic series in school notebooks and shares it with the younger children "
     "in her home. An art teacher at the youth center says she has a real talent for storytelling. A drawing "
     "tablet would let her learn digital illustration."),

    # --- L'Oriental ---
    ("oujda", "M", (2, 5), "family_in_difficulty", "essentials", 550, "high", "open",
     ["winter", "heating", "cold"],
     "A heater for a cold one-room apartment",
     "An electric heater safe for a small room with young children.",
     "{name} is {age} and lives with his parents and baby brother in a single room. Winters in the region are "
     "harsh and the walls are thin. Last January, {name} was ill for most of the month. A safe heater would "
     "keep the room warm through the cold season."),
    ("oujda", "F", (12, 14), "family_in_difficulty", "education", 450, "high", "partial",
     ["school", "transport", "education"],
     "School transport for one term",
     "A seat on the school minibus for three months.",
     "{name}, {age}, lives in a village outside the city and her middle school is twelve kilometers away. "
     "The minibus costs more than her family can pay each month. Without it, she would have to drop out, "
     "like her older sister did. One term of transport would keep her in school."),
    ("oujda", "M", (6, 9), "family_in_difficulty", "clothing", 400, "high", "almost",
     ["winter", "clothing", "siblings"],
     "Warm clothes for two brothers",
     "Coats, sweaters and warm socks for two young brothers.",
     "{name}, {age}, and his younger brother share one coat and take turns wearing it. The cold wave is "
     "expected to hit the region soon. Their mother works in a textile workshop but her salary barely covers "
     "rent. Warm clothes would let both boys go outside without freezing."),
    ("oujda", "F", (6, 10), "family_in_difficulty", "food", 500, "medium", "funded",
     ["food", "family", "ramadan"],
     "A basket of staples for the month",
     "Flour, oil, sugar, tea, rice and dates for a family of five.",
     "{name}'s family lives on her grandmother's small pension. At the end of the month, meals often come down "
     "to bread and tea. {name}, {age}, told her teacher she was not hungry so she would not be noticed. "
     "A month of staples helped the whole family eat properly."),
    ("oujda", "M", (4, 6), "chronic_illness", "health", 1000, "medium", "open",
     ["health", "speech", "therapy"],
     "Speech therapy sessions",
     "Ten sessions with a speech therapist before he starts school.",
     "{name}, {age}, speaks only a few words and gets frustrated when he cannot make himself understood. A "
     "doctor recommended speech therapy before he starts school next year. The nearest therapist is in the "
     "city and the sessions are not covered. Ten sessions could make a lasting difference."),

    # --- Fès-Meknès ---
    ("fes", "F", (11, 14), "orphan", "creative", 300, "low", "open",
     ["creativity", "calligraphy", "culture"],
     "A calligraphy set and lessons",
     "Reed pens, ink, paper and a term of calligraphy lessons.",
     "{name}, {age}, watches the calligrapher near her children's home every afternoon. He offered to teach "
     "her if she has her own tools. She practices with a ballpoint pen on old newspapers in the meantime. "
     "A proper set would turn her curiosity into a skill."),
    ("fes", "M", (8, 10), "family_in_difficulty", "education", 210, "medium", "open",
     ["school", "supplies", "geometry"],
     "School supplies and a geometry kit",
     "Notebooks, a geometry set, colored pencils and a dictionary.",
     "{name}, {age}, is in a class where every pupil needs a geometry kit for math lessons. He borrows one "
     "when he can and often misses exercises when he cannot. His father repairs shoes and earns very little "
     "in winter. A full set of supplies would make school easier for him."),
    ("fes", "M", (12, 16), "chronic_illness", "health", 900, "high", "partial",
     ["health", "mobility", "disability"],
     "A wheelchair repair and a pressure cushion",
     "New wheels, brakes and a medical cushion for daily use.",
     "{name}, {age}, uses a wheelchair that was donated years ago. The brakes no longer work and the wheels are "
     "worn, so he stays home on rainy days. The hard seat has started to cause sores. A repair and a proper "
     "cushion would let him get to school safely."),
    ("fes", "F", (0, 1), "family_in_difficulty", "family_care", 450, "medium", "open",
     ["baby", "clothing", "newborn"],
     "Newborn clothes and a baby carrier",
     "Clothes for the first months and a carrier for the long walks.",
     "{name} was born a few weeks ago into a family that had not planned for a third child. Her parents had "
     "to sell their furniture last year to pay debts. They have almost nothing prepared for her. Clothes and "
     "a carrier would help them through the first months."),
    ("fes", "M", (13, 15), "temporary_placement", "sport", 350, "low", "open",
     ["sport", "athletics", "running"],
     "A tracksuit and running shoes for athletics",
     "A tracksuit and proper running shoes for the athletics club.",
     "{name}, {age}, won the cross-country race organized by his youth center. The regional athletics club "
     "invited him to train with them. He runs in worn sneakers that hurt his feet. Proper shoes and a tracksuit "
     "would let him take the chance."),
]

# Two suspicious submissions for the trust-check demo (status pending_review).
SUSPICIOUS_WISHES = [
    {
        "title": "A school bag for the new year",
        "description": "A complete school bag with all supplies for the year.",
        "story_context": "My daughter starts school soon and needs a bag with everything inside. "
                         "We cannot afford it this year. Please help her start the year well.",
        "category": "education", "estimated_cost": 5000, "urgency": "medium",
        "city": "Casablanca", "region": "Casablanca-Settat",
        "tags": ["school", "supplies"],
        "raw_submission": "salam, bghit cartable kamel l bnti, fih kolchi. taman 5000 dh. "
                          "ana Samira, tel 06 00 00 00 00",
    },
    {
        "title": "School supplies for my daughter",
        "description": "A bag, notebooks and pens for the school year.",
        # Nearly copies the story of the first Casablanca wish on purpose.
        "story_context": "She is 8 and starts the new school year in a few weeks. Her mother cleans offices at night "
                         "and this month's money has already gone to rent. Last year she shared notebooks with her "
                         "cousin and often could not do her homework. A bag of her own would let her start the year "
                         "like everyone else.",
        "category": "education", "estimated_cost": 190, "urgency": "medium",
        "city": "Casablanca", "region": "Casablanca-Settat",
        "tags": ["school", "supplies", "back-to-school"],
        "raw_submission": "My daughter needs school supplies for this year, she is 8 and starts in a few weeks.",
    },
]

# Mock crisis news (shown as "Sample data" in the app).
NEWS = [
    ("Violent storm hits Ouarzazate",
     "Heavy rain and strong winds damaged dozens of homes in and around Ouarzazate. "
     "Families need shelter materials and food while roads are repaired.",
     "Drâa-Tafilalet", 4, ["shelter", "food"], 1),
    ("Cold wave expected in L'Oriental",
     "Temperatures are forecast to drop sharply across the region next week. "
     "Families in poorly insulated housing need heating and warm clothes.",
     "L'Oriental", 3, ["essentials", "clothing", "shelter"], 2),
    ("Back-to-school costs weigh on families in Casablanca",
     "Rising prices for supplies and books are pushing many families to delay purchases. "
     "Associations report more requests for school kits than last year.",
     "Casablanca-Settat", 2, ["education"], 4),
    ("Flash floods damage homes near Agadir",
     "Sudden flooding hit several neighborhoods on the outskirts of Agadir. "
     "Local associations are collecting bedding, essentials and repair materials.",
     "Souss-Massa", 3, ["shelter", "essentials"], 6),
    ("Heatwave puts pressure on families in Marrakech",
     "An early heatwave is affecting children with chronic conditions. "
     "Health associations call for help with medication and treatment costs.",
     "Marrakech-Safi", 3, ["health"], 8),
    ("Early winter in the Middle Atlas",
     "Snow arrived weeks ahead of schedule in the mountains around Fès and Meknès. "
     "Families in rural areas need warm clothing and heating.",
     "Fès-Meknès", 3, ["clothing", "essentials"], 10),
    ("Rising food prices hit families in Tangier",
     "Staple food prices have risen for three months in a row. "
     "Associations see more families asking for food baskets and baby supplies.",
     "Tanger-Tétouan-Al Hoceïma", 2, ["food", "family_care"], 12),
]


def clean_phone():
    return f"+212 6{random.randint(10000000, 99999999)}"


def iso(dt):
    return dt.replace(microsecond=0).isoformat()


def gen_organizations():
    orgs, by_key = [], {}
    for key, (name, org_type, city, region, verified) in ORGANIZATIONS.items():
        org = {
            "id": str(uuid.uuid4()),
            "name": name,
            "org_type": org_type,
            "contact_name": fake.name(),
            "contact_phone": clean_phone(),
            "contact_email": f"contact.{key}@example.org",
            "city": city,
            "region": region,
            "relay_point": f"Relay point — {name}, {city}",
            "is_verified": verified,
            "verification_doc_url": None,
            "country": "Morocco",
            "country_code": "MA",
            "created_at": iso(NOW - timedelta(days=random.randint(120, 700))),
        }
        orgs.append(org)
        by_key[key] = org
    return orgs, by_key


def split_amount(total, parts):
    """Split an integer amount into `parts` positive integers summing exactly to total."""
    if parts == 1 or total < parts * 10:
        return [total]
    cuts = sorted(random.sample(range(10, total - 9), parts - 1))
    values = [b - a for a, b in zip([0] + cuts, cuts + [total])]
    return values if all(v > 0 for v in values) else [total]


def raised_for(funding, cost):
    if funding == "open":
        return 0
    if funding == "partial":
        return int(round(cost * random.uniform(0.2, 0.6) / 5) * 5)
    if funding == "almost":
        return int(round(cost * random.uniform(0.80, 0.95) / 5) * 5)
    return cost  # funded / delivered


def status_for(funding, raised, cost):
    if funding == "delivered":
        return "delivered"
    if raised >= cost:
        return "funded"
    return "partially_funded" if raised > 0 else "open"


def gen_donors(n=15):
    donors = []
    for i in range(n):
        first, last = fake.first_name(), fake.last_name()
        donors.append({
            "id": str(uuid.uuid4()),
            "full_name": f"{first} {last}",
            "email": f"{first.lower()}.{last.lower()}{i}@example.org",
            "phone": clean_phone(),
            "preferred_categories": random.sample(
                ["education", "essentials", "health", "food", "shelter", "family_care", "sport"], k=2),
            "total_donated": 0,
            "created_at": iso(NOW - timedelta(days=random.randint(60, 360))),
        })
    return donors


def gen_wishes_and_donations(orgs_by_key, donors):
    beneficiaries, wishes, donations = [], [], []
    used_names = {"F": set(), "M": set()}
    donor_totals = {d["id"]: 0 for d in donors}

    for (key, gender, ages, situation, category, cost, urgency, funding, tags,
         title, description, story) in WISHES:
        org = orgs_by_key[key]
        pool = GIRL_NAMES if gender == "F" else BOY_NAMES
        free = [n for n in pool if n not in used_names[gender]] or pool
        nickname = random.choice(free)
        used_names[gender].add(nickname)
        age = random.randint(*ages)

        beneficiary = {
            "id": str(uuid.uuid4()),
            "organization_id": org["id"],
            "nickname": nickname,
            "age": age,
            "gender": gender,
            "situation": situation,
            "health_note": "Regular medical follow-up" if category == "health" else None,
            "created_at": iso(NOW - timedelta(days=random.randint(30, 200))),
        }
        beneficiaries.append(beneficiary)

        created = NOW - timedelta(days=random.randint(3, 120))
        raised = raised_for(funding, cost)
        wish_id = str(uuid.uuid4())

        # Donations always add up exactly to amount_raised.
        for amount in split_amount(raised, random.randint(1, 3)) if raised > 0 else []:
            donor = random.choice(donors)
            donor_totals[donor["id"]] += amount
            donations.append({
                "id": str(uuid.uuid4()),
                "donor_id": donor["id"],
                "wish_id": wish_id,
                "amount": amount,
                "donated_at": iso(created + timedelta(days=random.randint(0, 2), hours=random.randint(1, 20))),
                "message": random.choice([None, "Wishing you all the best!", "With love.", "For your smile.", None]),
                "donor_display_name": random.choice([donor["full_name"].split()[0], None]),
                "is_demo": False,
            })

        wishes.append({
            "id": wish_id,
            "beneficiary_id": beneficiary["id"],
            "organization_id": org["id"],
            "category": category,
            "title": title,
            "description": description,
            "story_context": story.format(name=nickname, age=age),
            "estimated_cost": cost,
            "amount_raised": raised,
            "currency": "MAD",
            "urgency": urgency,
            "status": status_for(funding, raised, cost),
            "relay_point": org["relay_point"],
            "city": org["city"],
            "region": org["region"],
            "country": "Morocco",
            "country_code": "MA",
            "tags": tags,
            "deadline": (NOW + timedelta(days=random.randint(7, 60))).date().isoformat()
            if urgency in ("high", "critical") and funding not in ("funded", "delivered") else None,
            "submission_source": "seed",
            "created_at": iso(created),
        })

    for d in donors:
        d["total_donated"] = donor_totals[d["id"]]
    return beneficiaries, wishes, donations


def gen_suspicious_wishes():
    rows = []
    for s in SUSPICIOUS_WISHES:
        rows.append({
            "id": str(uuid.uuid4()),
            "beneficiary_id": None,
            "organization_id": Raw(f"(SELECT id FROM organizations WHERE name = '{PLACEHOLDER_ORG}')"),
            "category": s["category"],
            "title": s["title"],
            "description": s["description"],
            "story_context": s["story_context"],
            "estimated_cost": s["estimated_cost"],
            "amount_raised": 0,
            "currency": "MAD",
            "urgency": s["urgency"],
            "status": "pending_review",
            "relay_point": "To be confirmed",
            "city": s["city"],
            "region": s["region"],
            "country": "Morocco",
            "country_code": "MA",
            "tags": s["tags"],
            "deadline": None,
            "submission_source": "ai_intake",
            "raw_submission": s["raw_submission"],
            "created_at": iso(NOW - timedelta(hours=random.randint(2, 30))),
        })
    return rows


def gen_news():
    return [{
        "id": str(uuid.uuid4()),
        "title": title,
        "summary": summary,
        "country": "Morocco",
        "country_code": "MA",
        "region": region,
        "severity": severity,
        "needed_categories": needed,
        "published_on": (NOW - timedelta(days=days_ago)).date().isoformat(),
        "is_mock": True,
    } for title, summary, region, severity, needed, days_ago in NEWS]


# ------------------------------------------------------------
# SQL output
# ------------------------------------------------------------
ENUM_ARRAY_COLUMNS = {
    "preferred_categories": "wish_category[]",
    "needed_categories": "wish_category[]",
}


def escape(val, col_name=None):
    if isinstance(val, Raw):
        return str(val)
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, list):
        items = ",".join("'" + str(v).replace("'", "''") + "'" for v in val)
        literal = f"ARRAY[{items}]"
        if col_name in ENUM_ARRAY_COLUMNS:
            literal += f"::{ENUM_ARRAY_COLUMNS[col_name]}"
        return literal
    return "'" + str(val).replace("'", "''") + "'"


def to_sql_inserts(table, rows):
    if not rows:
        return ""
    cols = list(rows[0].keys())
    values = ",\n".join("    (" + ", ".join(escape(r[c], c) for c in cols) + ")" for r in rows)
    return f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n{values};\n"


def main():
    orgs, orgs_by_key = gen_organizations()
    donors = gen_donors()
    beneficiaries, wishes, donations = gen_wishes_and_donations(orgs_by_key, donors)
    suspicious = gen_suspicious_wishes()
    news = gen_news()

    with open("seed_data.json", "w", encoding="utf-8") as f:
        json.dump({
            "organizations": orgs,
            "beneficiaries": beneficiaries,
            "wishes": wishes,
            "pending_wishes": [{**w, "organization_id": None, "organization_name": PLACEHOLDER_ORG}
                               for w in suspicious],
            "donors": donors,
            "donations": donations,
            "news_items": news,
        }, f, ensure_ascii=False, indent=2)

    with open("seed_data.sql", "w", encoding="utf-8") as f:
        f.write("-- GOLDEN WISHES — generated demo data (generate_seed_data.py)\n")
        f.write("-- Run AFTER schema.sql and migrations/001_golden_wishes_features.sql\n\n")
        f.write("BEGIN;\n\n")
        f.write("-- amount_raised already matches the donations below: the donation trigger\n")
        f.write("-- is disabled during the import so nothing is counted twice.\n")
        f.write("ALTER TABLE donations DISABLE TRIGGER trg_apply_donation;\n\n")
        f.write(to_sql_inserts("organizations", orgs) + "\n")
        f.write(to_sql_inserts("beneficiaries", beneficiaries) + "\n")
        f.write(to_sql_inserts("wishes", wishes) + "\n")
        f.write(to_sql_inserts("wishes", suspicious) + "\n")
        f.write(to_sql_inserts("donors", donors) + "\n")
        f.write(to_sql_inserts("donations", donations) + "\n")
        f.write(to_sql_inserts("news_items", news) + "\n")
        f.write("ALTER TABLE donations ENABLE TRIGGER trg_apply_donation;\n")
        f.write("UPDATE wishes SET title = title;  -- recompute rag_text\n\n")
        f.write("COMMIT;\n")

    print(f"Generated {len(orgs)} organizations")
    print(f"Generated {len(beneficiaries)} beneficiaries")
    print(f"Generated {len(wishes)} wishes + {len(suspicious)} pending (suspicious) wishes")
    print(f"Generated {len(donors)} donors")
    print(f"Generated {len(donations)} donations")
    print(f"Generated {len(news)} news items")
    print("\nFiles created: seed_data.sql, seed_data.json")


if __name__ == "__main__":
    main()
